---
title: "curi_draft"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)

library(tidyverse)
library(MutationalPatterns)
library(NMF)
library(reshape2)
library(grid)
library(gridExtra)
library(ggpubr)
library(ggrepel)
library(broom)
library(stringr)
```


Getting signature data from COSMIC for making constraints
```{r}
library(data.table)
cosmic_sig1 <- fread("https://cog.sanger.ac.uk/cosmic-signatures-production/documents/v3.2_SBS1_TISSUE.txt")

url1 <- "https://cog.sanger.ac.uk/cosmic-signatures-production/documents/v3.2_"
  url2 <- "_TISSUE.txt"
  url <- paste(url1, as.character("SBS1"), url2, sep="", collapse=NULL)
test <- fread(url)

get_sig_data <- function(A){
  
  url1 <- "https://cog.sanger.ac.uk/cosmic-signatures-production/documents/v3.2_"
  url2 <- "_TISSUE.txt"
  url <- paste(url1, as.character(A), url2, sep="", collapse=NULL)
  cosmic_sig <- fread(url)
  cosmic_sig
}

SBS1 <- get_sig_data("SBS1")
SBS2 <- get_sig_data("SBS2")
```

Getting Ranges from signature data
```{r}
test1 <- SBS1 %>%
  filter(Scale == "exome", Cancer.Types == "Breast") %>%
  mutate(mutations = SBS1.Mutations,
         prob = (mutations/50))
quantile(test1$prob)

test2 <- SBS1 %>%
  filter(Scale == "genome", Cancer.Types == "Breast") %>%
  mutate(mutations = SBS1.Mutations,
         prob = (mutations/3000))
range2 <- quantile(test2$prob)
range2[c(2,4)]


#trying to make it into a function
get_range <- function(data, scale, cancer_type, mutations_name){
  
  data_test <- data %>%
    filter(Scale == scale, Cancer.Types == cancer_type) %>%
    mutate(prob = ifelse(Scale == "genome", ({{ mutations_name }}/3000), ({{ mutations_name }}/50)))
  range <- quantile(data_test$prob)
  range[c(2,4)]
}

SBS1_test <- SBS1 %>%
  filter(Scale == "exome", Cancer.Types == "Breast") %>%
    mutate(prob = ifelse(Scale == "genome", (SBS1.Mutations/3000), (SBS1.Mutations/50)))
  range <- quantile(SBS1_test$prob)
  range[c(2,4)]
  

get_range(SBS1, "exome", "Skin-SCC", SBS1.Mutations)
```



```{r}
SBS1 <- get_sig_data("SBS1")
SBS2 <- get_sig_data("SBS2")
SBS3 <- get_sig_data("SBS3")


test_merge <- merge(SBS1, SBS2, SBS3, all = TRUE)

all_cosmic_data <- fread("https://cog.sanger.ac.uk/cosmic-signatures-production/documents/COSMIC_v3.3_SBS_GRCh38.txt")

SBS4 <- get_sig_data("SBS4")
SBS5 <- get_sig_data("SBS5")
SBS6 <- get_sig_data("SBS6")
SBS7a	<- get_sig_data("SBS7a")
SBS7b	<- get_sig_data("SBS7b")
SBS7c	<- get_sig_data("SBS7c")
SBS7d	<- get_sig_data("SBS7d")
SBS8	<- get_sig_data("SBS8")
SBS9	<- get_sig_data("SBS9")
SBS10a	<- get_sig_data("SBS10a")
SBS10b	<- get_sig_data("SBS10b")
#SBS10c	<- get_sig_data("SBS10c")
#SBS10d	<- get_sig_data("SBS10d")
SBS11	<- get_sig_data("SBS11")
SBS12	<- get_sig_data("SBS12")
SBS13	<- get_sig_data("SBS13")
SBS14	<- get_sig_data("SBS14")
SBS15	<- get_sig_data("SBS15")
SBS16	<- get_sig_data("SBS16")
SBS17a	<- get_sig_data("SBS17a")
SBS17b	<- get_sig_data("SBS17b")
SBS18	<- get_sig_data("SBS18")
SBS19	<- get_sig_data("SBS19")
SBS20	<- get_sig_data("SBS20")
SBS21	<- get_sig_data("SBS21")
SBS22	<- get_sig_data("SBS22")
SBS23	<- get_sig_data("SBS23")
SBS24	<- get_sig_data("SBS24")
#SBS25	<- get_sig_data("SBS25")
SBS26	<- get_sig_data("SBS26")

SBS27	<- get_sig_data("SBS27")
SBS28	<- get_sig_data("SBS28")
SBS29	<- get_sig_data("SBS29")
SBS30	<- get_sig_data("SBS30")
SBS31	<- get_sig_data("SBS31")
SBS32	<- get_sig_data("SBS32")
SBS33	<- get_sig_data("SBS33")
SBS34	<- get_sig_data("SBS34")
SBS35	<- get_sig_data("SBS35")
SBS36	<- get_sig_data("SBS36")
SBS37	<- get_sig_data("SBS37")
SBS38	<- get_sig_data("SBS38")
SBS39	<- get_sig_data("SBS39")
SBS40	<- get_sig_data("SBS40")
SBS41	<- get_sig_data("SBS41")
SBS42	<- get_sig_data("SBS42")
SBS43	<- get_sig_data("SBS43")
SBS44	<- get_sig_data("SBS44")
SBS45	<- get_sig_data("SBS45")
SBS46	<- get_sig_data("SBS46")
SBS47	<- get_sig_data("SBS47")
#SBS48	<- get_sig_data("SBS48")
SBS49	<- get_sig_data("SBS49")
SBS50	<- get_sig_data("SBS50")
SBS51	<- get_sig_data("SBS51")
SBS52	<- get_sig_data("SBS52")
SBS53	<- get_sig_data("SBS53")
SBS54	<- get_sig_data("SBS54")
SBS55	<- get_sig_data("SBS55")
SBS56	<- get_sig_data("SBS56")
SBS57	<- get_sig_data("SBS57")

SBS58	<- get_sig_data("SBS58")
SBS59	<- get_sig_data("SBS59")
SBS60	<- get_sig_data("SBS60")
#SBS84	<- get_sig_data("SBS84")
#SBS85	<- get_sig_data("SBS85")
#SBS86	<- get_sig_data("SBS86")
#SBS87	<- get_sig_data("SBS87")
#SBS88	<- get_sig_data("SBS88")
#SBS89	<- get_sig_data("SBS89")
#SBS90	<- get_sig_data("SBS90")
#SBS91	<- get_sig_data("SBS91")
#SBS92	<- get_sig_data("SBS92")
#SBS93	<- get_sig_data("SBS93")
#SBS94 <- get_sig_data("SBS94")

test_join1 <- full_join(SBS1, SBS2)
test_join2 <- full_join(test_join1, SBS3)
test_join3 <- full_join(test_join2, SBS4)
test_join4 <- full_join(test_join3, SBS5)
test_join5 <- full_join(test_join4, SBS6)
test_join6 <- full_join(test_join5, SBS7a)
test_join7 <- full_join(test_join6, SBS7b)
test_join8 <- full_join(test_join7, SBS7c)
test_join9 <- full_join(test_join8, SBS7d)
test_join10 <- full_join(test_join9, SBS8)
test_join11 <- full_join(test_join10, SBS9)
test_join13 <- full_join(test_join11, SBS10a)
test_join14 <- full_join(test_join13, SBS10b)
test_join16 <- full_join(test_join14, SBS11)
test_join17 <- full_join(test_join16, SBS11)
test_join18 <- full_join(test_join17, SBS12)
test_join19 <- full_join(test_join18, SBS13)
test_join21 <- full_join(test_join19, SBS14)
test_join22 <- full_join(test_join21, SBS15)
test_join23 <- full_join(test_join22, SBS16)

test_join24 <- full_join(test_join23, SBS17a)
test_join25 <- full_join(test_join24, SBS17b)
test_join26 <- full_join(test_join25, SBS18)
test_join27 <- full_join(test_join26, SBS19)
test_join28 <- full_join(test_join27, SBS20)
test_join22 <- full_join(test_join28, SBS21)
test_join22 <- full_join(test_join22, SBS22)
test_join22 <- full_join(test_join22, SBS23)
test_join22 <- full_join(test_join22, SBS24)
test_join22 <- full_join(test_join22, SBS26)
test_join22 <- full_join(test_join22, SBS27)
test_join22 <- full_join(test_join22, SBS28)
test_join22 <- full_join(test_join22, SBS29)
test_join22 <- full_join(test_join22, SBS30)
test_join22 <- full_join(test_join22, SBS31)
test_join22 <- full_join(test_join22, SBS32)
test_join22 <- full_join(test_join22, SBS33)
test_join22 <- full_join(test_join22, SBS34)
test_join22 <- full_join(test_join22, SBS35)
test_join22 <- full_join(test_join22, SBS36)
test_join22 <- full_join(test_join22, SBS37)
test_join22 <- full_join(test_join22, SBS38)
test_join22 <- full_join(test_join22, SBS39)
test_join22 <- full_join(test_join22, SBS40)
test_join22 <- full_join(test_join22, SBS41)
test_join22 <- full_join(test_join22, SBS42)
test_join22 <- full_join(test_join22, SBS43)
test_join22 <- full_join(test_join22, SBS44)
test_join22 <- full_join(test_join22, SBS45)
test_join22 <- full_join(test_join22, SBS46)
test_join22 <- full_join(test_join22, SBS47)
test_join22 <- full_join(test_join22, SBS49)
test_join22 <- full_join(test_join22, SBS50)
test_join22 <- full_join(test_join22, SBS51)
test_join22 <- full_join(test_join22, SBS52)
test_join22 <- full_join(test_join22, SBS53)
test_join22 <- full_join(test_join22, SBS54)
test_join22 <- full_join(test_join22, SBS55)
test_join22 <- full_join(test_join22, SBS56)
test_join22 <- full_join(test_join22, SBS57)
test_join22 <- full_join(test_join22, SBS58)
test_join22 <- full_join(test_join22, SBS59)
final_join <- full_join(test_join22, SBS60)

final_join[is.na(final_join)] <- 0

COSMICsample_ds <- final_join

list1 <- final_join %>%
  group_by(Cancer.Types) %>%
  summarize(n = n())

constraints_ds <- read_csv("Data/constraints_ds.csv")

constraints_ds <- constraints_ds %>%
  mutate(Tissue = ifelse(cancer.type == "Biliary-AdenoCA", "CHOL", 
                         ifelse(cancer.type == "Bladder-TCC", "BLCA",
                         ifelse(cancer.type == "Breast", "BRCA",
                         ifelse(cancer.type == "Cervix", "CESC",
                         ifelse(cancer.type == "CNS-GBM", "GBM",
                         ifelse(cancer.type == "ColoRect-AdenoCA", "COAD",
                         ifelse(cancer.type == "Eso-AdenoCA", "ESCA",
                         ifelse(cancer.type == "Eye-Melanoma", "UVM",
                         ifelse(cancer.type == "Head-SCC", "HNSC",
                         ifelse(cancer.type == "Kidney-ChRCC", "KICH",
                         ifelse(cancer.type == "Kidney-Papillary", "KIRP",
                         ifelse(cancer.type == "Kidney-RCC", "KIRC", 
                         ifelse(cancer.type == "Liver-HCC", "LIHC", 
                         ifelse(cancer.type == "Lung-AdenoCA", "LUAD", 
                         ifelse(cancer.type == "Lung-SCC", "LUSC", 
                         ifelse(cancer.type == "Lymph-BNHL", "DLBC", 
                         ifelse(cancer.type == "Myeloid-AML", "LAML", 
                         ifelse(cancer.type == "Ovary-AdenoCA", "OV",
                         ifelse(cancer.type == "Panc-AdenoCA", "PAAD",
                         ifelse(cancer.type == "Prost-AdenoCA", "PRAD",
                         ifelse(cancer.type == "Sarcoma", "SARC", 
                         ifelse(cancer.type == "Skin-Melanoma", "SKCM", 
                         ifelse(cancer.type == "Stomach-AdenoCA", "STAD",
                         ifelse(cancer.type == "Thy-AdenoCA", "THCA",
                         ifelse(cancer.type == "Uterus-AdenoCA", "UCS", cancer.type)))))))))))))))))))))))))) %>%
  rename(signature = "Signature",
         scale = "Scale",
         quantile = "Value")

constraints_ds <- constraints_ds %>%
  select("Quantile", "Signature", "Scale", "Value", "Tissue")

comparison_list <- c("CHOL", "BLCA", "BRCA", "CESC", "GBM", "COAD", "ESCA", "UVM", "HNSC", "KICH", "KIRP", "KIRC", "LIHC", "LUAD", "LUSC", "DLBC", "LAML", "OV", "PAAD", "PRAD", "SARC", "SKCM", "STAD", "THCA", "UCS")

comparison_list <- as.data.frame(comparison_list)

constraints_ds <- left_join(comparison_list, constraints_ds, by = c("comparison_list" = "Tissue"))

constraints_ds <- constraints_ds %>%
  rename(comparison_list = "Tissue")

constraints_ds[is.na(constraints_ds)] <- 0

write.csv(COSMICsample_ds, "Data/COSMICsample_ds.csv", row.names=FALSE)

constraints_ds <- unique(constraints_ds)

write.csv(constraints_ds, "Data/constraints_ds.csv", row.names=FALSE)
```



