---
title: "curi_draft"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)

library(tidyverse)
library(MutationalPatterns)
library(NMF)
library(reshape2)
library(grid)
library(gridExtra)
library(ggpubr)
library(ggrepel)
library(broom)
library(data.table)
```


Getting signature data from COSMIC for making constraints
```{r}
get_sig_data <- function(A){
  
  url1 <- "https://cog.sanger.ac.uk/cosmic-signatures-production/documents/v3.2_"
  url2 <- "_TISSUE.txt"
  url <- paste(url1, as.character(A), url2, sep="", collapse=NULL)
  cosmic_sig <- fread(url)
  cosmic_sig
}
```

Creating dataset
```{r}
SBS1 <- get_sig_data("SBS1")
cosmic.signatures <- get_known_signatures()

sigs <- colnames(cosmic.signatures)
unknown <- c("SBS10c", "SBS10d", "SBS25", "SBS48", "SBS84", "SBS85", "SBS86", "SBS87", "SBS88", "SBS89", "SBS90", "SBS91", "SBS92", "SBS93", "SBS94")
sigs <- sigs[ - which(sigs %in% unknown)]
scales <- c("genome", "exome")
cancer.types <- unique(SBS1$Cancer.Types)

exome <- SBS1 %>%
  filter(Scale == "exome")

genome <- SBS1 %>%
  filter(Scale == "genome")

exome.cancer.types <-  unique(exome$Cancer.Types)
genome.cancer.types <-  unique(genome$Cancer.Types)
```

```{r}
constraints_df <- c()
final_df <- c()
exome_df <- c()
genome_df <- c()  

for (i in 1:length(sigs)){
  SBS_df <- get_sig_data(sigs[i])
  
  for (j in 1:length(scales)){
    if (scales[j] == "exome"){
        for (k in 1:length(cancer.types)){
        
          df <- SBS_df %>%
            filter(Scale == scales[j], Cancer.Types == cancer.types[k])
          
          df <- as.matrix(df)
          mut <- df[,ncol(df)]
          mut <- as.numeric(unlist(mut))/50
          
          signature <- sigs[i]
          scale <- scales[j]
          cancer.type <- cancer.types[k]
          quantile <- quantile(mut, probs = seq(0.05, 0.95, 0.05))
          
          df <- cbind(signature, scale, cancer.type, quantile)
          exome_df <- rbind(exome_df, df)
      }
    }
    
    else if (scales[j] == "genome") {
        for (k in 1:length(cancer.types)){
        
          df <- SBS_df %>%
            filter(Scale == scales[j], Cancer.Types == cancer.types[k])
          
          df <- as.matrix(df)
          mut <- df[,ncol(df)]
          mut <- as.numeric(unlist(mut))/3000
          
          signature <- sigs[i]
          scale <- scales[j]
          cancer.type <- cancer.types[k]
          quantile <- quantile(mut, probs = seq(0.05, 0.95, 0.05))
          
          df <- cbind(signature, scale, cancer.type, quantile)
          genome_df <- rbind(genome_df, df)
      }
    }
  }
  final_df <- rbind(exome_df, genome_df)
  constraints_df <- rbind(constraints_df, final_df)
}
```

```{r}
constraints_df <- cbind(Quantile = rownames(constraints_df), constraints_df)
rownames(constraints_df) <- seq(1, dim(constraints_df)[1])
constraints_df <- as.data.frame(constraints_df)

constraints_df <- constraints_df %>%
  drop_na(quantile)

#write.csv(constraints_df, "Data/constraints_ds.csv", row.names=FALSE)
```


