---
title: "curi_draft"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)

library(tidyverse)
library(MutationalPatterns)
library(NMF)
library(reshape2)
library(grid)
library(gridExtra)
library(ggpubr)
library(ggrepel)
library(broom)
library(stringr)
library(data.table)
```


Getting signature data from COSMIC for sample profiles
```{r}
get_sig_data <- function(A){
  
  url1 <- "https://cog.sanger.ac.uk/cosmic-signatures-production/documents/v3.2_"
  url2 <- "_TISSUE.txt"
  url <- paste(url1, as.character(A), url2, sep="", collapse=NULL)
  cosmic_sig <- fread(url)
  cosmic_sig
}
```

Extracting sample data from COSMIC website
```{r}
SBS1 <- get_sig_data("SBS1")
SBS2 <- get_sig_data("SBS2")
SBS3 <- get_sig_data("SBS3")
SBS4 <- get_sig_data("SBS4")
SBS5 <- get_sig_data("SBS5")
SBS6 <- get_sig_data("SBS6")
SBS7a	<- get_sig_data("SBS7a")
SBS7b	<- get_sig_data("SBS7b")
SBS7c	<- get_sig_data("SBS7c")
SBS7d	<- get_sig_data("SBS7d")
SBS8	<- get_sig_data("SBS8")
SBS9	<- get_sig_data("SBS9")
SBS10a	<- get_sig_data("SBS10a")
SBS10b	<- get_sig_data("SBS10b")
#SBS10c	<- get_sig_data("SBS10c")
#SBS10d	<- get_sig_data("SBS10d")
SBS11	<- get_sig_data("SBS11")
SBS12	<- get_sig_data("SBS12")
SBS13	<- get_sig_data("SBS13")
SBS14	<- get_sig_data("SBS14")
SBS15	<- get_sig_data("SBS15")
SBS16	<- get_sig_data("SBS16")
SBS17a	<- get_sig_data("SBS17a")
SBS17b	<- get_sig_data("SBS17b")
SBS18	<- get_sig_data("SBS18")
SBS19	<- get_sig_data("SBS19")
SBS20	<- get_sig_data("SBS20")
SBS21	<- get_sig_data("SBS21")
SBS22	<- get_sig_data("SBS22")
SBS23	<- get_sig_data("SBS23")
SBS24	<- get_sig_data("SBS24")
#SBS25	<- get_sig_data("SBS25")
SBS26	<- get_sig_data("SBS26")

SBS27	<- get_sig_data("SBS27")
SBS28	<- get_sig_data("SBS28")
SBS29	<- get_sig_data("SBS29")
SBS30	<- get_sig_data("SBS30")
SBS31	<- get_sig_data("SBS31")
SBS32	<- get_sig_data("SBS32")
SBS33	<- get_sig_data("SBS33")
SBS34	<- get_sig_data("SBS34")
SBS35	<- get_sig_data("SBS35")
SBS36	<- get_sig_data("SBS36")
SBS37	<- get_sig_data("SBS37")
SBS38	<- get_sig_data("SBS38")
SBS39	<- get_sig_data("SBS39")
SBS40	<- get_sig_data("SBS40")
SBS41	<- get_sig_data("SBS41")
SBS42	<- get_sig_data("SBS42")
SBS43	<- get_sig_data("SBS43")
SBS44	<- get_sig_data("SBS44")
SBS45	<- get_sig_data("SBS45")
SBS46	<- get_sig_data("SBS46")
SBS47	<- get_sig_data("SBS47")
#SBS48	<- get_sig_data("SBS48")
SBS49	<- get_sig_data("SBS49")
SBS50	<- get_sig_data("SBS50")
SBS51	<- get_sig_data("SBS51")
SBS52	<- get_sig_data("SBS52")
SBS53	<- get_sig_data("SBS53")
SBS54	<- get_sig_data("SBS54")
SBS55	<- get_sig_data("SBS55")
SBS56	<- get_sig_data("SBS56")
SBS57	<- get_sig_data("SBS57")

SBS58	<- get_sig_data("SBS58")
SBS59	<- get_sig_data("SBS59")
SBS60	<- get_sig_data("SBS60")
#SBS84	<- get_sig_data("SBS84")
#SBS85	<- get_sig_data("SBS85")
#SBS86	<- get_sig_data("SBS86")
#SBS87	<- get_sig_data("SBS87")
#SBS88	<- get_sig_data("SBS88")
#SBS89	<- get_sig_data("SBS89")
#SBS90	<- get_sig_data("SBS90")
#SBS91	<- get_sig_data("SBS91")
#SBS92	<- get_sig_data("SBS92")
#SBS93	<- get_sig_data("SBS93")
#SBS94 <- get_sig_data("SBS94")

sig_join <- full_join(SBS1, SBS2)
sig_join <- full_join(sig_join, SBS3)
sig_join <- full_join(sig_join, SBS4)
sig_join <- full_join(sig_join, SBS5)
sig_join <- full_join(sig_join, SBS6)
sig_join <- full_join(sig_join, SBS7a)
sig_join <- full_join(sig_join, SBS7b)
sig_join <- full_join(sig_join, SBS7c)
sig_join <- full_join(sig_join, SBS7d)
sig_join <- full_join(sig_join, SBS8)
sig_join <- full_join(sig_join, SBS9)
sig_join <- full_join(sig_join, SBS10a)
sig_join <- full_join(sig_join, SBS10b)
sig_join <- full_join(sig_join, SBS11)
sig_join <- full_join(sig_join, SBS11)
sig_join <- full_join(sig_join, SBS12)
sig_join <- full_join(sig_join, SBS13)
sig_join <- full_join(sig_join, SBS14)
sig_join <- full_join(sig_join, SBS15)
sig_join <- full_join(sig_join, SBS16)
sig_join <- full_join(sig_join, SBS17a)
sig_join <- full_join(sig_join, SBS17b)
sig_join <- full_join(sig_join, SBS18)
sig_join <- full_join(sig_join, SBS19)
sig_join <- full_join(sig_join, SBS20)
sig_join <- full_join(sig_join, SBS21)
sig_join <- full_join(sig_join, SBS22)
sig_join <- full_join(sig_join, SBS23)
sig_join <- full_join(sig_join, SBS24)
sig_join <- full_join(sig_join, SBS26)
sig_join <- full_join(sig_join, SBS27)
sig_join <- full_join(sig_join, SBS28)
sig_join <- full_join(sig_join, SBS29)
sig_join <- full_join(sig_join, SBS30)
sig_join <- full_join(sig_join, SBS31)
sig_join <- full_join(sig_join, SBS32)
sig_join <- full_join(sig_join, SBS33)
sig_join <- full_join(sig_join, SBS34)
sig_join <- full_join(sig_join, SBS35)
sig_join <- full_join(sig_join, SBS36)
sig_join <- full_join(sig_join, SBS37)
sig_join <- full_join(sig_join, SBS38)
sig_join <- full_join(sig_join, SBS39)
sig_join <- full_join(sig_join, SBS40)
sig_join <- full_join(sig_join, SBS41)
sig_join <- full_join(sig_join, SBS42)
sig_join <- full_join(sig_join, SBS43)
sig_join <- full_join(sig_join, SBS44)
sig_join <- full_join(sig_join, SBS45)
sig_join <- full_join(sig_join, SBS46)
sig_join <- full_join(sig_join, SBS47)
sig_join <- full_join(sig_join, SBS49)
sig_join <- full_join(sig_join, SBS50)
sig_join <- full_join(sig_join, SBS51)
sig_join <- full_join(sig_join, SBS52)
sig_join <- full_join(sig_join, SBS53)
sig_join <- full_join(sig_join, SBS54)
sig_join <- full_join(sig_join, SBS55)
sig_join <- full_join(sig_join, SBS56)
sig_join <- full_join(sig_join, SBS57)
sig_join <- full_join(sig_join, SBS58)
sig_join <- full_join(sig_join, SBS59)
final_join <- full_join(sig_join, SBS60)

final_join[is.na(final_join)] <- 0

COSMICsample_ds <- final_join

#constraints_ds <- read_csv("Data/constraints_ds.csv")
```