---
title: "FiguresStacie"
output: html_document
date: "2022-07-25"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)

library(tidyverse)
library(MutationalPatterns)
library(NMF)
library(reshape2)
library(grid)
library(gridExtra)
library(ggpubr)
library(ggrepel)
library(broom)
library(emplik)
library(glmc)
library(ConsReg)
library(Hmisc)
library(yardstick)
library(reshape2)
library(ggrepel)
```

```{r Method Figures (unfinished)}
#Load the P3, Sig10,6,5 data
p3 <- read_csv("Data/P3_sig.csv")
mutational_sig <- read_csv("mutational_sig_oec/supplied_data/mutational.sig.csv")

p3_withcontext <- mutational_sig %>%
  filter(sample == "s1133903279") %>%
  select(1,4,7) %>%
  mutate(p3 = prob + 0.0001) %>%
  select(1,3,4)

p3_withcontext <- tibble::rowid_to_column(p3_withcontext, "ID")

p3 <- tibble::rowid_to_column(p3, "ID")

p3_final <- full_join(p3, p3_withcontext, by = "ID")

p3_final <- p3_final %>%
  mutate(p3 = p3.x) %>%
  select(2:4, 7, 9)

#plot1, maybe work on window size?
ggplot(p3_final, aes(x = sig10, y = p3, label = ext.context)) +
  geom_point(alpha = 0.3) + 
  geom_text(data = subset(p3_final, p3 > 0.12 & sig10 < 0.1), aes(p3,sig10,label=ext.context), hjust = 4, vjust = -20.5) +
  geom_text(data = subset(p3_final, p3 > 0.14 & sig10 > 0.2), aes(p3,sig10,label=ext.context), hjust = -2, vjust = 12) +
  geom_text(data = subset(p3_final, sig10 > 0.3), aes(p3,sig10,label=ext.context), hjust = -7.25, vjust = 44) +
  geom_smooth(method = "lm", color = "mediumpurple3", level = 0.5) +
  labs(title = "Sample Profile Against SBS10", 
       x = "SBS10",
       y = "Sample Profile") +
  theme_bw() +
  theme(plot.title = element_text(size = 15, hjust = 0.5, face = "bold")) +
  theme(panel.grid.minor.x = element_line(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_line(),
        panel.grid.major.y = element_blank())

ggsave("method1.png", device='png', dpi=700)

#plot2
ggplot(p3_final, aes(x = sig6, y = p3)) +
  geom_point(alpha = 0.3) +
  geom_text(data = subset(p3_final, p3 > 0.12 & sig6 < 0.1), aes(p3,sig6,label=ext.context), hjust = 5.75, vjust = -29) +
  geom_text(data = subset(p3_final, p3 > 0.12 & sig6 > 0.1), aes(p3,sig6,label=ext.context), hjust = 1.75, vjust = -8) +
  geom_smooth(method = "lm", color = "mediumpurple3", level = 0.5) +
  labs(title = "Plot of Sample Profile Against SBS6", 
       x = "SBS6",
       y = "Sample Profile") +
  theme_bw() +
  theme(plot.title = element_text(size = 15, hjust = 0.5, face = "bold")) +
  theme(panel.grid.minor.x = element_line(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_line(),
        panel.grid.major.y = element_blank())

ggsave("method2.png", device='png', dpi=700)
```

$$Sample Profile = \beta_1SBS6 + \beta_2SBS10 $$
$$x \leq \beta_1 \leq y$$
$$x \leq \beta_2 \leq y$$


```{r Ignore?}
data1 <- data %>%
  pivot_longer(
    cols = c(`sig10`, `sig6`, `sig1`),
    names_to = "signatures", 
    values_to = "prob"
  )

#plot2
ggplot(data1, aes(x = prob, y = p3, color = signatures)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(
    y = "Mutation prob of P3",
    x = "Mutation prob of Sig",
    title = "Contribution of Signatures to the Profile P3"
  ) +
  theme(axis.text.x = element_text(color = "grey20", size = 17, angle = 0, hjust = 1, vjust = 0, face = "plain"), axis.text.y = element_text(color = "grey20", size = 17, angle = 0, hjust = 1, vjust = 0, face = "plain"), axis.title = element_text(size = 17), plot.title = element_text(size=22), legend.text=element_text(size=17), legend.title =element_text(size=17)) 
```

```{r Result Figures}
eval_df <- read_csv("Data/evaluation_ds.csv")

#Result Figure1 (work on title)
ggplot(data = eval_df, aes(x = expected_list, y = actual_list, label = sig_list))+
   geom_point(alpha=0.3) +
   geom_text(data = subset(eval_df, expected_list > 0.79 & actual_list < 0.6), aes(expected_list,actual_list,label=sig_list), hjust= -0.1, vjust= 1) +
   geom_smooth(method = "lm", color = "mediumpurple3") +
   labs(x = "Results from Dissolvo", 
        y = "True Proportions",
        title = "Comparison of Dissolvo Output and 
Sample Colorectal Cancer Profiles") +
  theme_bw() +
  theme(plot.title = element_text(size = 15, hjust = 0.5, face = "bold")) +
  theme(panel.grid.minor.x = element_line(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_line(),
        panel.grid.major.y = element_blank())

ggsave("result1.png", device='png', dpi=700)

cor(eval_df$expected_list, eval_df$actual_list)
cor(eval_df$fitsig_list, eval_df$actual_list)


sig_levels <- c("SBS1", "SBS5", "SBS15", "SBS40", "SBS44")
eval_df2 <- eval_df %>%
  mutate(sig_list = factor(sig_list, sig_levels)) %>%
  group_by(sig_list) %>%
  mutate(n = n()) %>%
  filter(n > 65 & !is.na(sig_list))

#Result Figure2 (work on title but i think it's pretty)
ggplot(data = eval_df2, aes(x = expected_list, y = actual_list))+
   geom_point(alpha=0.3) +
   geom_smooth(method = "lm", color = "mediumpurple3") +
   facet_wrap(~sig_list) +
   labs(x = "Results from Dissolvo", y = "True Proportions", title = "Dissolvo Output and Sample Profiles
of Selected Mutational Signatures") +
  theme_bw() +
  theme(plot.title = element_text(size = 15, hjust = 0.5, face = "bold")) +
  theme(panel.grid.minor.x = element_line(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_line(),
        panel.grid.major.y = element_blank())

ggsave("result2.png", device='png', dpi=700)

acc <- read_csv("Data/all_cancer_correlation.csv")

#Result Figure3
ggplot(data = acc, aes(x = all_corr)) +
  geom_histogram(stat = "bin", position = "identity", bins = 7, color = "black", fill = "#D1C4E9") + 
  labs(x = "Correlation Values", y = "Count", title = "Correlations between Dissolvo and 
True Proportion for Ten Cancer Types") +
  theme_bw() +
  theme(plot.title = element_text(size = 15, hjust = 0.5, face = "bold")) +
  theme(panel.grid.minor.x = element_line(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_line(),
        panel.grid.major.y = element_blank())

x <- factor(c("apple", "bear", "banana", "dear"))
fct_recode(x, fruit = "apple", fruit = "banana")

acc <- acc %>%
  mutate(all_cancer = fct_recode(all_cancer,
                                 "Lung" = "Lung_cancer",
                                 "Head" = "Head_cancer",
                                 "Bladder" = "Bladder_cancer", 
                                 "Skin" = "Skin_cancer",
                                 "Liver" = "Liver_cancer",
                                 "Uterus" = "Uterus_cancer",
                                 "Breast" = "Breast_cancer",
                                 "Colorectal" = "Colorectal_cancer", 
                                 "Stomach" = "Stomach_cancer",
                                 "Prostate" = "Prostate_cancer"))

ggplot(acc, aes(y= all_corr, x= fct_reorder(all_cancer, all_corr))) + 
    geom_bar(position="dodge", stat="identity", color = "black", fill = "#D1C4E9" ) +
  labs(x = "Cancer Type", y = "Correlation Values", title = "Correlations between Dissolvo and 
True Proportion for Ten Cancer Types") +
  coord_flip(ylim=c(0.92,1)) +
  theme_bw() +
  theme(plot.title = element_text(size = 15, hjust = 0.5, face = "bold")) +
  theme(panel.grid.minor.x = element_line(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_line(),
        panel.grid.major.y = element_blank())


ggsave("result3.png", device='png', dpi=700)
```
