---
title: "TestingStacie"
output: html_document
date: '2022-07-11'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(MutationalPatterns)
library(NMF)
library(reshape2)
library(grid)
library(gridExtra)
library(ggpubr)
library(ggrepel)
library(broom)
library(emplik)
library(glmc)
library(ConsReg)

sample_info <- read_csv("mutational_sig_oec/supplied_data/sample.info.csv")
```

# Necessary Functions
```{r}
estimate_coeff <- function(sample_profile, sigs, tissue_type, scale, quantiles, mb_size){
  
  #parameters testing
  #sample_profile <- generate_sample_prof(c("SBS1","SBS10b","SBS6"),c(100,300,600))
  total_mut <- unname(colSums(sample_profile)[1])
  
  sample_profile <- as.matrix(sample_profile[,2])
  colnames(sample_profile) <- c("prob")
  
  #sigs <- c("SBS1","SBS10b","SBS6")
  #tissue_type <- "BRCA"
  #scale <- "exome"
  #quantiles <- c("5%","95%")
  #mb_size <- 50
  
  #pulling constraints
  constraints_ds <- read_csv("Data/constraints_ds.csv")
  constr1 <- constraints_ds %>%
    filter(Tissue == tissue_type, Signature %in% sigs, Scale == scale, Quantile %in% quantiles) 
  constrs <- c(constr1$Value)
  
  #making dataset for the model
  cosmic.signatures <- get_known_signatures()
  sig <- cosmic.signatures[,sigs]
  
  df <- cbind(sample_profile,sig)
  df <- as_tibble(df)
  
  constraints <- str_c(constrs[1]*(mb_size/total_mut), ' < ', sigs[1], ', ', sigs[1], ' < ', constrs[2]*(mb_size/total_mut))
  for (i in 2:length(sigs)){
    constraint <- str_c(constrs[2*i-1]*(mb_size/total_mut), ' < ', sigs[i], ', ', sigs[i], ' < ', constrs[2*i]*(mb_size/total_mut))
    constraints <- str_c(constraints, ', ', constraint)
  }
  
  model<- ConsReg(formula = prob ~ 0 + ., data = df,
            family = 'gaussian',
            constraints = constraints
            )
  
  model$coefficients
  #coeff <- as.tibble(model$coefficients)
  #coeff$value
}

# Load mutational signature data for all samples
signatures <- read_csv(
    "mutational_sig_oec/supplied_data/mutational.sig.csv")

# Load sequencing/cohort info for samples, filter with at
# at least 5 million Mb covered
sample.info <-
    read_csv("mutational_sig_oec/supplied_data/sample.info.csv") %>%
    filter (area.cov > 5e6)

generate_sample_prof <- function(sigs, nums){

  #sigs <- c("SBS10a","SBS10b","SBS10c","SBS6")
  #nums <- c(100,100,100,700)
  
  cosmic.signatures <- get_known_signatures()
  sig <- cosmic.signatures[,sigs]
  
  #load the mutation order
  mut.selected <- sample.info %>%
    select (sample) %>%
    inner_join (signatures)
  
  mut.order="mutational_sig_oec/supplied_data/mut_sig.order.csv"
  mutational.signature <-  mut.selected
  mut_mat <-  read_csv(mut.order)
  
  mut.join <-  mutational.signature %>%
    inner_join(mut_mat)
  order.tri <-  unique(mut.join$ext.context)
  
  rownames(sig) <- order.tri
  mut_order <- as_tibble(order.tri)
  
  
  df_a <- c()
  #generate from the first signature to the last signatures and merge with the first signature
  for (i in 1:length(sigs)){
    b <- sample(rownames(sig), size = nums[i], replace = TRUE, prob = sig[,i])
    df_b <- as_tibble(b)
    df_b <- df_b %>%
      count(value) %>%
      mutate(
        value = factor(value, levels = order.tri),
      ) %>%
      merge(mut_order, all = TRUE)
    
    df_b[is.na(df_b)] <- 0     # Replace NA with 0
    df_b <- df_b %>%
      select(-value)
    
    #rownames(df_b) <- order.tri
    df_b <- as.matrix(df_b)
    
    df_a <- cbind(df_a, df_b)
  }
  
  df_a <- rowSums(df_a)
  df_a <- as_tibble(df_a)
  colnames(df_a) <- c("mut")

  sample_profile <- df_a %>%
    mutate(
      prob = mut/sum(mut)
    )
  sample_profile <- as.matrix(sample_profile)
  rownames(sample_profile) <- order.tri
  
  sample_profile
}
```

Testing
```{r}
#loading in COSMIC sample data
COSMICsample_ds <- read_csv("Data/COSMICsample_ds.csv")

#getting just colorectal cancer samples
colo_samples <- COSMICsample_ds %>%
  filter(Cancer.Types == "ColoRect-AdenoCA")

#creating sample SP18310
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS44"),c(33221,25724,49282))
proptable1 <- prop.table(c(33221,25724,49282))
test1 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS44"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP17172
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS44"),c(31717,46279,46366))
proptable2 <- prop.table(c(31717,46279,46366))
test2 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS44"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP96133
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS44"),c(13278,36824,31246))
proptable3 <- prop.table(c(13278,36824,31246))
test3 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS44"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP110242
view(colo_samples[4,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS44"),c(14945,41590,57440))
proptable4 <- prop.table(c(14945,41590,57440))
test4 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS44"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP114330
view(colo_samples[5,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS18","SBS40"),c(2984,2400,2192,3232))
proptable5 <- prop.table(c(2984,2400,2192,3232))
test5 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS18","SBS40"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP21017
view(colo_samples[6,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS15","SBS44"),c(7861,33583,21789,25201))
proptable6 <- prop.table(c(7861,33583,21789,25201))
test6 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS15","SBS44"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP22383
view(colo_samples[7,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS44"),c(12546,49006,35926))
proptable7 <- prop.table(c(12546,49006,35926))
test7 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS44"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP81312
view(colo_samples[8,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS10a", "SBS10b", "SBS28"),c(27622,123696,286145,288758,81266))
proptable8 <- prop.table(c(27622,123696,286145,288758,81266))
test8 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS10a", "SBS10b", "SBS28"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP81312
view(colo_samples[9,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS10a", "SBS10b", "SBS28"),c(4441,18068,120638,41834,49250))
proptable9 <- prop.table(c(4441,18068,120638,41834,49250))
test9 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS10a", "SBS10b", "SBS28"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP96112
view(colo_samples[10,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS18"),c(1703,3604,1617))
proptable10 <- prop.table(c(1703,3604,1617))
test10 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS18"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP96112
view(colo_samples[11,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS44"),c(11321,46589,36994))
proptable11 <- prop.table(c(11321,46589,36994))
test11 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS44"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP96112
view(colo_samples[12,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS18", "SBS37","SBS40"),c(2734,628,8191,2916,9605))
proptable12 <- prop.table(c(2734,628,8191,2916,9605))
test12 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS18", "SBS37","SBS40"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP16886
view(colo_samples[13,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS10a", "SBS10b","SBS28"),c(2051,77687,406630,106952,255962))
proptable13 <- prop.table(c(2051,77687,406630,106952,255962))
test13 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS10a", "SBS10b","SBS28"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP96124
view(colo_samples[14,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS18"),c(2343,3829,3215))
proptable14 <- prop.table(c(2343,3829,3215))
test14 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS18"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP19295
view(colo_samples[15,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS10a","SBS10b","SBS28"),c(6240,30215,134596,44143,44673))
proptable15 <- prop.table(c(6240,30215,134596,44143,44673))
test15 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS10a","SBS10b","SBS28"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP19670
view(colo_samples[16,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS18"),c(2335,2858,6212))
proptable16 <- prop.table(c(2335,2858,6212))
test16 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS18"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP17905
view(colo_samples[17,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS10a","SBS10b","SBS28","SBS37"),c(3924,338607,946039,208495,607474,328078))
proptable17 <- prop.table(c(3924,338607,946039,208495,607474,328078))
test17 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS10a","SBS10b","SBS28","SBS37"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP17905
view(colo_samples[18,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS17a","SBS17b","SBS18","SBS37","SBS40"),c(1975,923,950,2355,3133,1469,6224))
proptable18 <- prop.table(c(1975,923,950,2355,3133,1469,6224))
test18 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS17a","SBS17b","SBS18","SBS37","SBS40"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP20993
view(colo_samples[19,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS18","SBS40"),c(3327,3389,2408,9421))
proptable19 <- prop.table(c(3327,3389,2408,9421))
test19 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS18","SBS40"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP19983
view(colo_samples[20,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS18","SBS40"),c(3681,1694,4108,12119))
proptable20 <- prop.table(c(3681,1694,4108,12119))
test20 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS18","SBS40"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP18121
view(colo_samples[21,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS37","SBS44"),c(6255,64017,25367,65500))
proptable21 <- prop.table(c(6255,64017,25367,65500))
test21 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS37","SBS44"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP18121
view(colo_samples[22,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS18"),c(2734,6193,10355))
proptable22 <- prop.table(c(2734,6193,10355))
test22 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS18"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP119755
view(colo_samples[23,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS18","SBS40"),c(2755,3795,5434,7291))
proptable23 <- prop.table(c(2755,3795,5434,7291))
test23 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS18","SBS40"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP96126
view(colo_samples[24,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS18"),c(3573,8907,6481))
proptable24 <- prop.table(c(3573,8907,6481))
test24 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS18"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP19606
view(colo_samples[25,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS17a","SBS17b","SBS28","SBS40"),c(2694,411,1452,5376,660,19555))
proptable25 <- prop.table(c(2694,411,1452,5376,660,19555))
test25 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS17a","SBS17b","SBS28","SBS40"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP19606
view(colo_samples[25,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS17a","SBS17b","SBS28","SBS40"),c(2694,411,1452,5376,660,19555))
proptable25 <- prop.table(c(2694,411,1452,5376,660,19555))
test25 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS17a","SBS17b","SBS28","SBS40"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP96118
view(colo_samples[26,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS44"),c(5746,6878,11947))
proptable26 <- prop.table(c(5746,6878,11947))
test26 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS44"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP21528
view(colo_samples[27,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS18"),c(3081,5446,3734))
proptable27 <- prop.table(c(3081,5446,3734))
test27 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS18"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP21400
view(colo_samples[28,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS10a","SBS10b","SBS28"),c(28611,178061,223491,210699,152178))
proptable28 <- prop.table(c(28611,178061,223491,210699,152178))
test28 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS10a","SBS10b","SBS28"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP23078
view(colo_samples[29,])
sample_prof <- generate_sample_prof(c("SBS1","SBS40"),c(2079,11337))
proptable29 <- prop.table(c(2079,11337))
test29 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS40"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)

#creating sample SP17430
view(colo_samples[30,])
sample_prof <- generate_sample_prof(c("SBS1","SBS5","SBS40"),c(2301, 1015,7254))
proptable30 <- prop.table(c(2301, 1015,7254))
test30 <- estimate_coeff(sample_prof, sigs = c("SBS1","SBS5","SBS40"), tissue_type = "COAD", scale = "genome", quantiles = c("5%", "95%"), mb_size = 3000)
```

#Making the values into a dataframe
```{r}
actual <- c(test1[1], test1[2], test1[3], test2[1], test2[2], test2[3], test3[1], test3[2], test3[3], test4[1], test4[2], test4[3], test5[1], test5[2], test5[3], test5[4], test6[1], test6[2], test6[3], test6[4], test7[1], test7[2], test7[3], test8[1], test8[2], test8[3], test8[4], test8[5], test9[1], test9[2], test9[3], test9[4], test9[5], test10[1], test10[2], test10[3], test11[1], test11[2], test11[3], test12[1], test12[2], test12[3], test12[4], test12[5], test13[1], test13[2], test13[3], test13[4], test13[5], test14[1], test14[2], test14[3], test15[1], test15[2], test15[3], test15[4], test15[5], test16[1], test16[2], test16[3], test17[1], test17[2], test17[3], test17[4], test17[5], test18[1], test18[2], test18[3], test18[4], test18[5], test18[6], test18[7], test19[1], test19[2], test19[3], test19[4], test20[1], test20[2], test20[3], test20[4], test21[1], test21[2], test21[3], test21[4], test22[1], test22[2], test22[3], test23[1], test23[2], test23[3], test23[4], test24[1], test24[2], test24[3], test25[1], test25[2], test25[3], test25[4], test25[5], test25[6], test26[1], test26[2], test26[3], test27[1], test27[2], test27[3], test28[1], test28[2], test28[3], test28[4], test28[5], test29[1], test29[2], test30[1], test30[2], test30[3], test826[1], test826[2], test825[1], test825[2], test825[3], test824[1], test824[2], test823[1], test823[2], test822[1], test822[2], test821[1], test821[2], test820[1], test820[2], test818[1], test818[2], test818[3], test818[4], test818[5], test817[1], test817[2], test816[1], test816[2], test815[1], test815[2], test814[1], test814[2], test813[1], test813[2], test812[1], test812[2], test811[1], test811[2], test810[1], test810[2], test809[1], test809[2], test808[1], test808[2], test807[1], test807[2], test806[1], test806[2], test805[1], test805[2], test804[1], test804[2], test803[1], test803[2], test802[1], test802[2], test801[1], test801[2], test800[1], test800[2])

expected <- c(proptable1[1], proptable1[2], proptable1[3], proptable2[1], proptable2[2], proptable2[3], proptable3[1], proptable3[2], proptable3[3], proptable4[1], proptable4[2], proptable4[3], proptable5[1], proptable5[2], proptable5[3], proptable5[4], proptable6[1], proptable6[2], proptable6[3], proptable6[4], proptable7[1], proptable7[2], proptable7[3], proptable8[1], proptable8[2], proptable8[3], proptable8[4], proptable8[5], proptable9[1], proptable9[2], proptable9[3], proptable9[4], proptable9[5], proptable10[1], proptable10[2], proptable10[3], proptable11[1], proptable11[2], proptable11[3], proptable12[1], proptable12[2], proptable12[3], proptable12[4], proptable12[5], proptable13[1], proptable13[2], proptable13[3], proptable13[4], proptable13[5], proptable14[1], proptable14[2], proptable14[3], proptable15[1], proptable15[2], proptable15[3], proptable15[4], proptable15[5], proptable16[1], proptable16[2], proptable16[3], proptable17[1], proptable17[2], proptable17[3], proptable17[4], proptable17[5], proptable18[1], proptable18[2], proptable18[3], proptable18[4], proptable18[5], proptable18[6], proptable18[7], proptable19[1], proptable19[2], proptable19[3], proptable19[4], proptable20[1], proptable20[2], proptable20[3], proptable20[4], proptable21[1], proptable21[2], proptable21[3], proptable21[4], proptable22[1], proptable22[2], proptable22[3], proptable23[1], proptable23[2], proptable23[3], proptable23[4], proptable24[1], proptable24[2], proptable24[3], proptable25[1], proptable25[2], proptable25[3], proptable25[4], proptable25[5], proptable25[6], proptable26[1], proptable26[2], proptable26[3], proptable27[1], proptable27[2], proptable27[3], proptable28[1], proptable28[2], proptable28[3], proptable28[4], proptable28[5], proptable29[1], proptable29[2], proptable30[1], proptable30[2], proptable30[3], proptable826[1], proptable826[2], proptable825[1], proptable825[2], proptable825[3], proptable824[1], proptable824[2], proptable823[1], proptable823[2], proptable822[1], proptable822[2], proptable821[1], proptable821[2], proptable820[1], proptable820[2], proptable818[1], proptable818[2], proptable818[3], proptable818[4], proptable818[5], proptable817[1], proptable817[2], proptable816[1], proptable816[2], proptable815[1], proptable815[2], proptable814[1], proptable814[2], proptable813[1], proptable813[2], proptable812[1], proptable812[2], proptable811[1], proptable811[2], proptable810[1], proptable810[2], proptable809[1], proptable809[2], proptable808[1], proptable808[2], proptable807[1], proptable807[2], proptable806[1], proptable806[2], proptable805[1], proptable805[2], proptable804[1], proptable804[2], proptable803[1], proptable803[2], proptable802[1], proptable802[2], proptable801[1], proptable801[2], proptable800[1], proptable800[2])

testing_data <- data.frame(actual, expected)

ggplot(data = testing_data, mapping = aes(x = expected, y = actual)) +
  geom_point()
```


