---
title: "Testing_Lung"
output: pdf_document
date: '2022-07-19'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)

library(tidyverse)
library(MutationalPatterns)
library(NMF)
library(reshape2)
library(grid)
library(gridExtra)
library(ggpubr)
library(ggrepel)
library(broom)
library(emplik)
library(glmc)
library(ConsReg)
library(Hmisc)
library(yardstick)

```


#Testing for Lung cancer, exome data
```{r}
COSMICsample_ds <- read_csv("~/Desktop/curi2022/Data/COSMICsample_ds.csv")
cosmic.signatures <- get_known_signatures()
tissue_list <- unique(COSMICsample_ds$Cancer.Types)
```

These are the signatures that the constraints are unknown in the COSMIC website.
```{r}
COSMICsample <- COSMICsample_ds %>%
  select(6:64) 
signature_list <- colnames(COSMICsample)
signature_list <- str_remove(signature_list, ".Mutations")
cosmic_signature_list <- colnames(cosmic.signatures)

known_sig <- signature_list[signature_list %in% cosmic_signature_list]
```


```{r}

COSMICsample_ds <- read_csv("~/Desktop/curi2022/Data/COSMICsample_ds.csv")
cosmic.signatures <- get_known_signatures()
tissue_list <- unique(COSMICsample_ds$Cancer.Types)

Lung_cancer_samples <- COSMICsample_ds %>%
  filter(Cancer.Types == "Lung-AdenoCA") %>%
  filter(Scale == "exome")

Lung_cancer_samples_withnames <- Lung_cancer_samples %>%
  select(4,6:64) 
Lung_cancer_samples <- Lung_cancer_samples %>%
  select(6:64) 
Lung_cancer_samples_size <- dim(Lung_cancer_samples)[1]

sample_names_list <- Lung_cancer_samples_withnames %>%
    select(1)
sample_names_list <- as.matrix(sample_names_list)
```


Making the final Dataframe for Lung cancer 


```{r}

actual_list <- c()
expected_list <- c()
fitsig_list <- c()
sig_list <- c()
sample_list <- c()

for (i in 1:Lung_cancer_samples_size){
  
  mut <- as.numeric(Lung_cancer_samples[i,])
  nonzero_sig <- (which(mut %nin% c(0, NA)))
  list <- colnames(Lung_cancer_samples)
  s_list <- list[nonzero_sig]
  s_list <- str_remove(s_list, ".Mutations")
  m_list <- mut[mut %nin% c(0, NA)]
  
  bool <- s_list %in% known_sig
  s_list <- s_list[bool]
  m_list <- m_list[bool]
  
  if(length(m_list) == 1){
    next
  }
  
  prop.test <- prop.table(m_list)
  
  neg_count <- 1
  while(neg_count != 0){
    sample_prof <- generate_sample_prof(s_list, m_list)
    model <- dissolvo(sample_prof, sigs = s_list, tissue_type = "LUAD", scale = "exome", quantiles = c("5%","95%"), mb_size = 50)
    coeff_list <- unname(model)
    neg_count <- sum(coeff_list < 0)
  }
  method_test <- model

  fit_test <- fit_to_signatures(sample_prof, cosmic.signatures[,s_list])
  fit_test <- fit_test$contribution[,2]
  
  sample_names <- c()
  for(j in 1:length(s_list)){
    sample_name <- sample_names_list[i]
    sample_names <- append(sample_names, sample_name)
  }
  
  sample_list <- append(sample_list, sample_names)
  actual_list <- append(actual_list, prop.test)
  expected_list <- append(expected_list, method_test)
  fitsig_list <- append(fitsig_list, fit_test)
  sig_list <- append(sig_list, s_list)
}

eval_df_4 <- cbind(sample_list, sig_list, expected_list, fitsig_list, actual_list)
eval_df_4 <- as_tibble(eval_df_4)
eval_df_4 <- eval_df_4 %>%
  mutate(
    expected_list = as.numeric(expected_list),
    fitsig_list = as.numeric(fitsig_list),
    actual_list = as.numeric(actual_list)
  )
``` 

```{r}
write.csv(eval_df_4, "Data/Lung_cancer_evaluation_ds.csv", row.names = FALSE)
```

Plot the Actual vs. Expected
```{r}
eval_df_4 <- read_csv("~/Desktop/curi2022/Data/Lung_cancer_evaluation_ds.csv")
ggplot(data = eval_df_4, mapping = aes(x = expected_list, y = actual_list))+
   geom_point(alpha=0.3)+
   geom_smooth(method = "lm")+
  facet_wrap(~sig_list)

cor(eval_df_4$expected_list, eval_df_4$actual_list)

cor(eval_df_4$actual_list, eval_df_4$fitsig_list)
```


```{r}
topcancer<-COSMICsample_ds %>%
  filter(SBS1.Mutations>0,
         SBS6.Mutations>0,
         SBS5.Mutations>0)%>%
  select(Cancer.Types,SBS1.Mutations,SBS6.Mutations,SBS5.Mutations)

```



Getting MSE between Expected vs. fit_to_signature vs. Actual
```{r}
mse_list_EF <- c()
mse_list_EA <- c()

for (i in 1:Lung_cancer_samples_size){
  
  mut <- as.numeric(Lung_cancer_samples[i,])
  nonzero_sig <- (which(mut %nin% c(0, NA)))
  list <- colnames(Lung_cancer_samples)
  s_list <- list[nonzero_sig]
  s_list <- str_remove(s_list, ".Mutations")
  m_list <- mut[mut %nin% c(0, NA)]
  
  bool <- s_list %in% known_sig
  s_list <- s_list[bool]
  m_list <- m_list[bool]
  
  if(length(m_list) == 1){
    next
  }
  
  sample_prof <- generate_sample_prof(s_list, m_list)
  prop_test <- prop.table(m_list)
  method_test <- estimate_coeff(sample_prof, sigs = s_list, tissue_type = "LUAD", scale = "exome", quantiles = c("5%", "95%"), mb_size = 50)
  
  if(length(s_list) == 1){
    cosmic_1sig <- as.matrix(cosmic.signatures[,s_list])
    colnames(cosmic_1sig) <- s_list
    
    fit_test <- fit_to_signatures_strict(sample_prof, cosmic_1sig, max_delta = 0.002)
    fit_test <- fit_test$fit_res$contribution
    fit_test <- fit_test[,2]
  } else{
    fit_test <- fit_to_signatures_strict(sample_prof, cosmic.signatures[,s_list], max_delta = 0.002)
    fit_test <- fit_test$fit_res$contribution
    fit_test <- fit_test[,2]
  }
  
  df <- cbind(fit_test, method_test)
  df <- as_tibble(df)
  mse <- rmse_vec(df$fit_test, df$method_test)^2
  mse_list_EF <- append(mse_list_EF, mse)
  
  df <- cbind(prop_test, method_test)
  df <- as_tibble(df)
  mse <- rmse_vec(df$prop_test, df$method_test)^2
  mse_list_EA <- append(mse_list_EA, mse)
}

Lung_cancer_sample_names <- unique(evaluation_ds$sample_list)
mse_df_4 <- cbind(Lung_cancer_sample_names, mse_list_EF, mse_list_EA)
mse_df_4 <- as_tibble(mse_df_4)
mse_df_4 <- mse_df_4 %>%
  mutate(
    mse_list_EF = as.numeric(mse_list_EF),
    mse_list_EA = as.numeric(mse_list_EA)
  )


```


```{r}
write.csv(mse_df_4, "Data/mse_ds_Lung_cancer.csv", row.names = FALSE)
```

Plotting MSE between Expected vs. fit_to_signature vs. Actual
```{r}
mse_df_4 <- read_csv("~/Desktop/curi2022/Data/mse_ds_Lung_cancer.csv")
```
```{r}
mean(mse_df_4$mse_list_EF)
mean(mse_df_4$mse_list_EA)

histogram(mse_df_4$mse_list_EF)
histogram(mse_df_4$mse_list_EA)

mse_df_4 %>%
  ggplot(aes(x = seq(1, dim(mse_df_4)[1]), y = mse_list_EA)) +
    geom_point() +
    labs(x = "samples", y = "MSE", title = "MSE between Expected and Actual value for Lung cancer") 

mse_df_4 %>%
  ggplot(aes(x = seq(1, dim(mse_df_4)[1]), y = mse_list_EF)) +
    geom_point() +
    labs(x = "samples", y = "MSE", title = "MSE between Expected and fit_to_signature value for Lung cancer") 
```

